const path = require('path')
const packages = path.resolve(__dirname, '../src/components')
// const commonpath = path.resolve(__dirname, "./commonTest")
const optionalComp = process.argv[process.argv.length - 1].split('--comp=') && process.argv[process.argv.length-1].split('--comp=')[1];
// const colors = require("colors/safe");
// colors.setTheme({
// 	silly: 'rainbow',
// 	input: 'grey',
// 	verbose: 'cyan',
// 	prompt: 'grey',
// 	info: 'green',
// 	data: 'grey',
// 	help: 'cyan',
// 	warn: 'yellow',
// 	debug: 'blue',
// 	error: 'red'
// });
// console.log(colors.info(`执行 ${optionalComp || '所有'}组件的测试`))
const allcomponents = [
  `${packages}/button`,
  `${packages}/input`,
  `${packages}/tag`,
  `${packages}/icon`,
  `${packages}/date-picker`,
  `${packages}/image`,
  `${packages}/image-viewer`,
  `${packages}/slider`,
  `${packages}/switch`,
  `${packages}/radio`,
  `${packages}/checkbox`,
  `${packages}/config-provider`,
  `${packages}/form-item-wrapper`,
  `${packages}/nav-bar`,
  `${packages}/search-bar`,
  `${packages}/empty`,
  `${packages}/modal`,
  `${packages}/dialog`,
  `${packages}/popup`,
  `${packages}/center-popup`,
  `${packages}/text-area`,
  `${packages}/toast`,
  `${packages}/loading`,
  `${packages}/notice`,
  // `${packages}/calendar`,
  `${packages}/cascader-view`,
  `${packages}/date-time-picker`,
  `${packages}/time-picker`,
  `${packages}/pull-to-refresh`,
  `${packages}/list`,
  `${packages}/infinite-scroll`,
  `${packages}/list`,
  `${packages}/tool-bar`,
  `${packages}/popover`,
  `${packages}/avatar`,
  `${packages}/accordion`,
  `${packages}/tabs`,
  `${packages}/tab-pane`,
  `${packages}/badge`,
  `${packages}/tab-bar`,
  `${packages}/steps`,
  `${packages}/progress-bar`,
  `${packages}/flex`,
  `${packages}/page-indicator`,
  `${packages}/swiper`,
  `${packages}/hyperlinks`,
  `${packages}/rate`,
  `${packages}/time-range-picker`,
  // `${packages}/calendar-picker-view`,
  `${packages}/skeleton`,
  `${packages}/divider`,
  `${packages}/index-bar`,
  `${packages}/swipe-action`,
  `${packages}/check-list`,
  `${packages}/picker`,
  `${packages}/result`,
  `${packages}/water-mark`,
  // `${packages}/error-block`,
  `${packages}/grid`,
  `${packages}/floating-panel`,
  `${packages}/space`,
  `${packages}/safe-area`,
  `${packages}/form`,
  `${packages}/mask`,
  `${packages}/ellipsis`,
  `${packages}/action-sheet`,
  `${packages}/selector`,
  `${packages}/dropdown`,
  `${packages}/input-number`,
  `${packages}/stepper`,
  `${packages}/picker-view`,
  `${packages}/card`,
  `${packages}/floating-bubble`,
  `${packages}/date-picker-view`,
  `${packages}/cascade-picker`,
  `${packages}/progress-circle`,
  `${packages}/side-bar`,
  `${packages}/error-message`,
  `${packages}/cascade-picker-view`,
];
const testComponents = allcomponents.filter(c => c.endsWith(optionalComp && optionalComp.toLowerCase()))
module.exports = testComponents.length ? testComponents : allcomponents
