const textMultiLangMap = {
    'ltr': {
        date: '日期',
        range: '日期范围',
        time: '时间',
        input: '文本输入框',
        search: '搜索框',
        password: '密码框',
        num: '数字输入框',
        textarea: '文本域',
        select: '下拉框',
        selectall: '全部',
        selectconfirming: '待确认',
        selectexecuting: '执行中',
        selectcompleted: '已办结',
        selecttermination: '终止',
        radio: '单选',
        china: '中国',
        usa: '美国',
        checkbox: '多选',
        billNo: '单据编号',
        billDate: '单据日期',
        billType: '业务类型',
        supplier: '供应商',
        contact: '联系人',
        warehouse: '仓库',
        total: '整单数量',
        money: '金额',
        billTypeValue: '普通采购',
        warehouseValue: '普通仓',
        add: "新增",
        edit: "编辑",
        del: "删除",
        treeSelect: "树选择",
        cascader: "级联选择",
        inputGroup: "输入框组",
        number: "数字输入框默认",
        rate: "评分",
        message: "消息提示",
        confirmTxt: "消息内容长文本测试",
        save: "确定",
        cancel: "取消",
        switch: "开关",
        slide: "滑块",
        slideReverse: "反向滑块",
        slideRange: "范围拖拽滑块",
        radioButton: "单选按钮组",

        print: "打印",
        else: "其他",
        import: "导入",
        export: "导出"


    },
    'rtl': {
        date: 'تاريخ',
        range: 'النطاق الزمني',
        time: 'وقت',
        input: 'مربع إدخال النص',
        search: 'مربع البحث',
        password: 'مربع كلمة المرور',
        num: 'صندوق إدخال الأرقام',
        textarea: 'حقل النص',
        select: 'المربع المنسدل',
        selectall: 'الجميع',
        selectconfirming: 'ليتم تأكيدها',
        selectexecuting: 'تنفيذ',
        selectcompleted: 'مكتمل',
        selecttermination: 'الإنهاء',
        radio: 'اختيار واحد',
        china: 'الصين',
        usa: 'الولايات المتحدة الأمريكية',
        checkbox: 'الاختيار من متعدد',
        billNo: 'رقم الوثيقة',
        billDate: 'تاريخ الوثيقة',
        billType: 'نوع العمل',
        supplier: 'مزود',
        contact: 'الشخص الذي يمكن الاتصال به',
        warehouse: 'مخزن',
        total: 'كمية الطلب كاملة',
        money: 'كمية',
        billTypeValue: 'شراء عادي',
        warehouseValue: 'مستودع عادي',
        add: "إضافة",
        edit: "تحرير",
        del: "حذف",
        treeSelect: "اختيار الشجرة",
        cascader: "تحديد متسلسل",
        inputGroup: "مجموعة حقول الإدخال",
        number: "الافتراضي لحقل الإدخال الرقمي",
        rate: "التقييم",
        message: "تنبيه رسالة",
        confirmTxt: "محتوى الرسالة: اختبار نص طويل",
        save: "الحفظة",
        cancel: "إلغاء",
        switch: "تفتح",
        slide: "مزلج",
        slideReverse: "مزلج عكسي",
        slideRange: "مزلج سحب المدى",
        radioButton: "مجموعة زرار اختيار واحد",
        print: "طباعة",
        else: "أخرى",
        import: "استيراد",
        export: "تصدير",

    }
}

export default textMultiLangMap;