export default {
    locale: 'ar',
    modal:{
        'ok': 'العنوان',
        'gotit': 'فهمت',
        'cancel': 'إلغاء',
        'title': 'موافق',
    },
    cascader: {
        'placeholder': 'اختر الرجاء',
        'notFoundContent': 'لا توجد بيانات',
    },
    colorpicker: {
        title: 'لوحة الألوان',
        ok: 'تأكيد',
        cancel: 'إلغاء',
    },
    
    calendar: {
        'today': 'اليوم',
        'now': 'الآن',
        'backToToday': 'رجوع لليوم',
        'ok': 'موافق',
        'clear': 'مسح',
        'month': 'شهر',
        'year': 'سنة',
        'timeSelect': 'اختيار الوقت',
        'dateSelect': 'اختيار التاريخ',
        'monthSelect': 'اختر شهرًا',
        'yearSelect': 'اختر سنة',
        'decadeSelect': 'اختر عقدًا',
        'yearFormat': 'YYYY',
        'dateFormat': 'DD/MM/YYYY',
        'dayFormat': 'DD',
        'dateTimeFormat': 'DD/MM/YYYY HH:mm:ss',
        'monthBeforeYear': 'true',
        'previousMonth': 'الشهر السابق (PageUp)',
        'nextMonth': 'الشهر التالي (PageDown)',
        'previousYear': 'السنة السابقة (Ctrl + اليسار)',
        'nextYear': 'السنة التالية (Ctrl + اليمين)',
        'previousDecade': 'العقد السابق',
        'nextDecade': 'العقد التالي',
        'previousCentury': 'القرن السابق',
        'nextCentury': 'القرن التالي',
        'clickSelectColomn': "انقر هنا لاختيار العمود",
        'clickSelect': "انقر هنا لاختيار",
        'date': "يوم",
        'toToday': "اليوم",
        'toLastDay': "اليوم السابق",
        'toNextDay': "اليوم التالي",
        'toLastMonth': "الشهر الماضي",
        'toNextMonth': "الشهر القادم",
        'allDay': "كل اليوم",
        'weekSelect': "اختيار أسبوع",
        months: [
            'يناير', 'فبراير', 'مارس', 'أبريل', 'مايو', 'يونيو', 
            'يوليو', 'أغسطس', 'سبتمبر', 'أكتوبر', 'نوفمبر', 'ديسمبر'
        ],
    weekdaysMin: ['الأ', 'الإ', 'الث', 'الر', 'الخ', 'الج', 'الس'],
    weekdaysShort: ['الأحد', 'الإثنين', 'الثلاثاء', 'الأربعاء', 'الخميس', 'الجمعة', 'السبت'],
    janFirst: 'يناير 1', 
    febFirst: 'فبراير 1',
    marFirst: 'مارس 1',
    aprFirst: 'أبريل 1',
    mayFirst: 'مايو 1',
    junFirst: 'يونيو 1',
    julFirst: 'يوليو 1',
    augFirst: 'أغسطس 1',
    sepFirst: 'سبتمبر 1',
    octFirst: 'أكتوبر 1',
    novFirst: 'نوفمبر 1',
    decFirst: 'ديسمبر 1',
           
    },
    clipboard: {
        'copy': 'نسخ',
        'cut': 'قص',
        'copyReady': 'تم النسخ',
        'cutReady': 'تم القص',
        'copyToClipboard': 'نسخ إلى الحافظة المؤقتة',
        'close': 'إغلاق',
    },
    inputNumber: {
        'msgMax': 'لا يمكن أن تكون القيمة أكبر من الأقصى',
        'msgMin': 'لا يجب أن تكون القيمة أقل من الأدنى',
    },
    spin: {
        'loading': 'جاري التحميل...',
    },
    treeSelect: {
        'notFoundContent': 'لا يوجد بيانات'
    },
    empty: {
        'noFound': '404',
        'noVisualizeDataImg': 'لا توجد بيانات حالياً ~',
        'noCollectImg': 'لا توجد مجموعات حالياً ~',
        'noDataImg': 'لا توجد بيانات حالياً ~',
        'noSearchImg': 'لم تقم بأي بحث حتى الآن ~',
        'noNetworkImg': 'لا يوجد اتصال بالإنترنت حالياً ~',
    },
    steps: {
        'text': 'إضافة',
    },
    
    select: {
        'notFoundContent': 'لا توجد بيانات حالياً'
    },
    
    image: {
        'prev': 'الصورة السابقة',
        'next': 'الصورة التالية',
        'zoomOut': 'تصغير',
        'zoomIn': 'تكبير',
        'fullscreen': 'FULLSCREEN', // 注意：通常“全屏”模式的标识会使用大写的“FULLSCREEN”，但也可以根据需要翻译成“الشاشة الكاملة”
        'rotateLeft': 'تدوير لليمين',
        'rotateRight': 'تدوير لليسار',
        'flipHorizontal': 'انعكاس أفقي',
        'flipVertical': 'انعكاس عمودي',
        'reset': 'إعادة تعيين',
        'play': 'تشغيل',
        'preview': 'معاينة',
    },
    transfer: {
        'notFoundContent': 'لا توجد بيانات',
        'source': 'قائمة المتاح',
        'target': 'قائمة المختارة',
        'searchPlaceholder': 'بحث',
    },
    table: {
            'resetSettings': 'إعادة تعيين الإعدادات',
            'include': 'يحتوي على',
            'exclusive': 'لا يحتوي على',
            'equal': 'مساوية لـ',
            'unequal': 'غير مساوية لـ',
            'end': 'تنتهي بـ',
            'greaterThan': 'أكبر من',
            'greatThanEqualTo': 'أكبر من أو مساوية لـ',
            'lessThan': 'أقل من',
            'lessThanEqualTo': 'أقل من أو مساوية لـ',
            'beEqualTo': 'مساوية لـ',
            'notEqualTo': 'غير مساوية لـ',
            "noData": 'لا يوجد بيانات حاليًا',
            "boolTrue": "نعم",
            "boolFalse": "لا",
            "total": "المجموع",
            'ok': 'تحديد',
            'cancel': 'إلغاء',
            'showRowNum': 'رقم السلسلة',
            'all': 'جميع',
            'searchNoRow': 'لم يتم العثور على أي صف مطابق!',
            'alreadyFirstRow': 'بالفعل الصف الأول المطابق!',
            'alreadyLastRow': 'بالفعل الصف الأخير المطابق!',
            'expandAll': 'نشر مجمع',
            'collapseAll': 'غلق مجمع',
            'overlayUpText': 'انقر للترتيب تصاعديا',
            'overlayDownText': 'انقر للترتيب تنازليا',
            'cancelOverlay': 'انقر لإلغاء الفرز',
            'selectAll': 'اختيار الكل',
            'invertCurrentPage': 'الاختيار العكسي للصفحة',
            'clearAll': 'مسح الكل'
    },
    datePicker: {
        'today': 'اليوم',
        'now': 'الآن',
        'backToToday': 'عودة إلى اليوم',
        'ok': 'تحديد',
        'timeSelect': 'اختر الوقت',
        'dateSelect': 'اختر تاريخًا',
        'weekSelect': 'اختر أسبوعًا',
        'clear': 'مسح',
        'month': 'شهر',
        'year': 'سنة',
        'previousMonth': 'الشهر الماضي',
        'nextMonth': 'الشهر التالي',
        'monthSelect': 'اختر شهرًا',
        'yearSelect': 'اختر سنة',
        'decadeSelect': 'اختر عقدًا',
        'firstHalfYear': 'النصف الأول من السنة',
        'secondHalfYear': 'النصف الثاني من السنة',
        'yearFormat': 'سنة yyyy',
        'quarterFormat': 'ربع Q',
        'quarter': 'ربع',
        'dayFormat': 'اليوم d',
        'dateFormat': 'Jyyy سنة m يوم J',
        'dateTimeFormat': 'Mm دقيقة ss ثانية في HH اليوم J من سنة YYY',
        'previousYear': 'السنة السابقة',
        'nextYear': 'السنة التالية',
        'previousDecade': 'العقود السابقة',
        'nextDecade': 'العقود التالية',
        'previousCentury': 'القرن السابق',
        'nextCentury': 'القرن التالي',
        months: ['شهر 1', 'شهر 2', 'شهر 3', 'شهر 4', 'شهر 5', 'شهر 6', 'شهر 7', 'شهر 8', 'شهر 9', 'شهر 10', 'شهر 11', 'شهر 12'],
        monthsShort: ['شهر 01', 'شهر 02', 'شهر 03', 'شهر 04', 'شهر 05', 'شهر 06', 'شهر 07', 'شهر 08', 'شهر 09', 'شهر 10', 'شهر 11', 'شهر 12'],
        weekdaysMin: ['الأحد', 'الاثنين', 'الثلاثاء', 'الأربعاء', 'الخميس', 'الجمعة', 'السبت'],
        weekdaysShort: ['الأحد', 'الاثنين', 'الثلاثاء', 'الأربعاء', 'الخميس', 'الجمعة', 'السبت'],
    },
    timePicker: {
        'ok': 'تحديد',
        'now': 'الآن',
        'clear': 'مسح',
    },
    popconfirm: {
        'ok': 'تأكيد',
        'cancel': 'إلغاء',
    },
    pagination: {
        'total': 'إجمالاً',
        'items': 'مقالة', 
    
        'show': 'عرض',
        'goto': 'انتقال إلى',
        'page': 'الصفحة',
        'ok': 'تحديد',
        'prev': 'الصفحة السابقة',
        'next': 'الصفحة التالية',
        'first': 'عودة إلى الصفحة الأولى',
        'last': 'انتقال إلى الصفحة الأخيرة',
    },
    upload: {
        'remove': 'حذف ملف',
        'down': 'تنزيل الملف',
        'fileLoading': 'جاري تحميل الملف',
        'toview': 'عرض الصورة الكبيرة',
        'preview': 'معاينة الصورة الكبيرة',
    },
}