/*
 * @Description:
 * @Author: supernever
 * @Date: 2021-04-20 15:17:27
 * @LastEditTime: 2024-03-26 19:19:19
 * @LastEditors: MJC
 */
export default {
    'wui-affix': require('../dist/wui-affix').default,
    'wui-alert': require('../dist/wui-alert').default,
    'wui-anchor': require('../dist/wui-anchor').default,
    'wui-autocomplete': require('../dist/wui-autocomplete').default,
    'wui-avatar': require('../dist/wui-avatar').default,
    'wui-backtop': require('../dist/wui-backtop').default,
    'wui-badge': require('../dist/wui-badge').default,
    'wui-breadcrumb': require('../dist/wui-breadcrumb').default,
    'wui-button': require('../dist/wui-button').default,
    'wui-button-group': require('../dist/wui-button-group').default, // 不提供
    'wui-calendar': require('../dist/wui-calendar').default,
    'wui-carousel': require('../dist/wui-carousel').default,
    'wui-cascader': require('../dist/wui-cascader').default,
    'wui-card': require('../dist/wui-card').default,
    'wui-checkbox': require('../dist/wui-checkbox').default,
    'wui-clipboard': require('../dist/wui-clipboard').default,
    'wui-collapse': require('../dist/wui-collapse').default,
    'wui-colorpicker': require('../dist/wui-colorpicker').default,
    'wui-datepicker': require('../dist/wui-datepicker').default,
    'wui-divider': require('../dist/wui-divider').default,
    'wui-drawer': require('../dist/wui-drawer').default,
    'wui-dropdown': require('../dist/wui-dropdown').default,
    'wui-empty': require('../dist/wui-empty').default,
    'wui-form': require('../dist/wui-form').default,
    'wui-icon': require('../dist/wui-icon').default,
    'wui-image': require('../dist/wui-image').default,
    'wui-input': require('../dist/wui-input').default,
    'wui-input-group': require('../dist/wui-input-group').default,
    'wui-input-number': require('../dist/wui-input-number').default,
    'wui-layout': require('../dist/wui-layout').default,
    'wui-list': require('../dist/wui-list').default,
    'wui-locale': require('../dist/wui-locale').default,
    'wui-menu': require('../dist/wui-menu').default,
    'wui-message': require('../dist/wui-message').default,
    'wui-error-message': require('../dist/wui-error-message').default,
    'wui-modal': require('../dist/wui-modal').default,
    'wui-notification': require('../dist/wui-notification').default,
    'wui-overlay': require('../dist/wui-overlay').default,
    'wui-pagination': require('../dist/wui-pagination').default,
    'wui-popconfirm': require('../dist/wui-popconfirm').default,
    'wui-popover': require('../dist/wui-popover').default,
    'wui-progress': require('../dist/wui-progress').default,
    'wui-provider': require('../dist/wui-provider').default,
    'wui-radio': require('../dist/wui-radio').default,
    'wui-rate': require('../dist/wui-rate').default,
    'wui-select': require('../dist/wui-select').default,
    'wui-skeleton': require('../dist/wui-skeleton').default,
    'wui-slider': require('../dist/wui-slider').default,
    'wui-spin': require('../dist/wui-spin').default,
    'wui-space': require('../dist/wui-space').default,
    'wui-steps': require('../dist/wui-steps').default,
    'wui-switch': require('../dist/wui-switch').default,
    'wui-svgicon': require('../dist/wui-svgicon').default,
    'wui-table': require('../dist/wui-table').default,
    'wui-tabs': require('../dist/wui-tabs').default,
    'wui-tag': require('../dist/wui-tag').default,
    'wui-timeline': require('../dist/wui-timeline').default,
    'wui-timepicker': require('../dist/wui-timepicker').default,
    'wui-tooltip': require('../dist/wui-tooltip').default,
    'wui-transfer': require('../dist/wui-transfer').default,
    'wui-tree': require('../dist/wui-tree').default,
    'wui-treeselect': require('../dist/wui-treeselect').default,
    'wui-typography': require('../dist/wui-typography').default,
    'wui-upload': require('../dist/wui-upload').default,
}
